---
name: Vacuum Tests

on:
  push:


jobs:
  pylint:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pip install requirements-dev.txt
      - name: Lint
        run: make lint

  vacuum:
    name: Vacuum Agents
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent_type: [1, 2, 3]
        include:
          - height: 10
          - width: 10
          - agent_type: 1
            height: 5
          - agent_type: 1
            width: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: pip install requirements.txt
      - name: Clean
        run: python vacuums.py ${{matrix.agent_type}} ${{matrix.height}} ${{matrix.width}}
